site_name: 'T-Invest API'
docs_dir: docs
repo_url: https://github.com/RussianInvestments/investAPI
theme:
  name: material
  custom_dir: overrides
  language: 'ru'
  palette:
    primary: black
    accent: yellow
  # custom_dir: swagger-iu/
plugins:
  - search:
      indexing: 'full'
      lang:
        - en
        - ru
      min_search_length: 3
      prebuild_index: false
      separator: "[\\s\\-]+"

nav:
- Начало работы: 
  - "Про T-Invest API": index.md
  - "Глоссарий": glossary.md
  - "Лимиты": limits.md
  - "Токен доступа": token.md
  - "Идентификация торговых инструментов": faq_identification.md
  - "Нестандартные типы данных": faq_custom_types.md
  - "Торговые статусы инструментов и расписание торгов": faq_trading_status.md
  - "Исторические данные": load_history.md
  - "Торговые поручения": orders_details.md
  - "Время исполнения запросов": deadlines.md
  - "Таблица параметров, возвращающих валюту или пункты": table_order_currency.md
  - "Популярные запросы и их решение": cases.md
  - "Конкурсные работы": robot_contest.md

- Протоколы:
  - "Доступные протoколы": api_protocols.md
  - "gRPC": grpc.md 
  - "WebSocket": ws\README.md
  - "Использование Swagger": swagger.md
 
- Полезная информация:
  - "Алгоритмическая торговля": algorithmic_trading.md
  - "Индикаторы технического анализа": tech_indicators.md
  - "Торговые площадки и режимы торгов": markets.md
  - "Торговля по выходным и на внутриброкерском рынке":
    - "Описание": weekend_trading.md
    - "Торговля по выходным": weekend.md
    - "Инструменты иностранных эмитентов": held_instruments.md
    - "Фонды Т-Банка": tbank_fund.md
  - "Квалифицированный инвестор": accredited_investor.md
  - "Правила обработки корпоративных действий": faq_corp_action.md
  - "Как ускорить работу с биржей": speedup.md
  - "Время жизни ключа и стрим-соединений": sla.md
  - "Примеры запросов": example.md
  - "Прекращение поддержки API v1": eol_v1.md
  - "Stream-соединения" : stream.md
  - "Цены облигаций и фьючерсов" : points.md
- Ответы на частые вопросы: faq.md
- SDK:
  - Python: faq_python.md
  - Java: faq_java.md
  - С#: faq_csharp.md
  - Golang: faq_golang.md
- Сервисы:
  - Счета: 
    - Описание: head-users.md
    - Методы: users.md
    - FAQ: faq_users.md
  - Инструменты:
    - Описание: head-instruments.md
    - Методы: instruments.md
    - Глоссарий и дополнительная информация: more-instrument.md
    - FAQ: faq_instruments.md
  - Заявки:
    - Описание: head-orders.md
    - Методы: orders.md
    - Таблица параметров, возвращающих валюту или пункты: table_order_currency.md
    - Стрим заявок: orders_state_stream.md
    - FAQ: faq_orders.md
  - Операции:
    - Описание: head-operations.md
    - Методы: operations.md
    - Особенности методов: operations_problems.md
    - FAQ: faq_operations.md
  - Котировки:
    - Описание: head-marketdata.md
    - Методы: marketdata.md
    - Исторические рыночные данные: get_history.md
    - Работа с индикаторами технического анализа: get_tech_indicators.md 
    - FAQ: faq_marketdata.md
  - Стоп-заявки: 
    - Описание: head-stoporders.md
    - Методы: stoporders.md
    - FAQ: faq_stoporders.md   
- Песочница:
  - Описание: head-sandbox.md
  - Методы: sandbox.md
  - Отличия контура песочницы: url_difference.md
  - FAQ: faq_sandbox.md
- Коды ошибок: 
  - "gRPC": errors.md 
  - "WebSocket": ws\errors.md
  - "HTTP": http_errors.md 